### ISSUE TITLE
Add docs for production deployment

### ISSUE THREAD

**Issue by seleckis** [strapi/one-click-deploy#10]
Please update documentation how to reconfigure image for production deployment. Now it runs in development mode and it is not clear how to make pm2 run in prod.

[Here](https://strapi.io/documentation/3.0.0-beta.x/installation/digitalocean-one-click.html) is written:
> To run the new production or staging environments you can refer to the PM2 Documentation.

Ok, but in PM2 documentation is mentioned ecosystem.config.js file, which I cannot find in currently running development mode.

**Comment by derrickmehaffy** [comment]
@seleckis We opted not to initially write documentation for this as it is highly subjective to the use-case (and there is a lot that goes into that)

- DNS for your domain
- Do you handle development locally, push into Git, then Deploy on the server? Or do you develop on the server, copy it into production on the same server? Or do you develop on the server, push into Git, and either reclone or clone/pull on a new server?
- As I'm the one to built the initial images, I personally don't care for the ecosystem.config.js files and instead opt to handle it via CLI, in which during a `pm2 save` there is a dump file that is created/updated that contains everything that a normal ecosystem file would have plus all the extra options.  However you can just as easily create one, remove the existing process ( `pm2 delete` ) and spin up a new one using the ecosystem.

What I believe should be done for moving into production is a community guide for doing so, much of Strapi is highly subjective to the users own use-case and some general purpose documentation will not be able to cover all the subjective flows that users may need or want for their deployment process. Though if you have some idea of what you are thinking of, I'm certainly open to suggestions.

---

Originally when these images were built, they were for newer users to get started using Strapi that may not have all the skills needed to deploy on their own (but hopefully would have the willing-ness to dig through and see how things were done) but wanted to testing Strapi before going through the whole deployment process. I never directly intended the images to be used in production without modification to the users use-case. For more experienced users, it's extremely likely they would rather deploy on their own, using their own deployment flows (such as in my own case, using ansible)

**Comment by seleckis** [comment]
Thank you for you detailed answer. I have walked around the code and found a quick possibility to make this installation kind of productional, just edit pm dump file and replace `develop` with `start`, this is enough for me.

Of course the production deployment can be different for different projects, but in this case the citation: 

> To run the new production or staging environments you can refer to the PM2 Documentation.

Which leads just to generic documentation of PM2, cannot help and does not make sense. That is why I asked about update. In my opinion this should be edited or removed to avoid confusion.

Anyway, thank you for your time.
