### ISSUE TITLE
BUILD FAILURE: Non-zero exit status: 100

### ISSUE THREAD

**Issue by mckhames** [strapi/one-click-deploy#15]
Build failed after 3 minutes, 9 seconds. Cannot install strapi one click on DigitalOcean. 

This is the output of the command: 

```
digital-ocean % packer build --var-file=variables.json template.json

```

==> digitalocean: Creating temporary RSA SSH key for instance...
==> digitalocean: Importing SSH public key...
==> digitalocean: Creating droplet...
==> digitalocean: Waiting for droplet to become active...
==> digitalocean: Using SSH communicator to connect: 157.245.252.1
==> digitalocean: Waiting for SSH to become available...
==> digitalocean: Connected to SSH!
==> digitalocean: Uploading configs/ => /tmp
==> digitalocean: Provisioning with shell script: scripts/1-install-depends.sh
    digitalocean: Doing updates to system
    digitalocean: Adding Node.js and Yarn repos
==> digitalocean: Warning: apt-key output should not be parsed (stdout is not a terminal)
    digitalocean: Installing Strapi package depends
    digitalocean: Installing Nginx
    digitalocean: Setting up PM2
==> digitalocean: warning pm2 > @pm2/io > @opencensus/core > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
==> digitalocean: warning pm2 > @pm2/io > @opencensus/propagation-b3 > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
==> digitalocean: warning pm2 > @pm2/io > @opencensus/propagation-b3 > @opencensus/core > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    digitalocean: Installing PostgreSQL
==> digitalocean: E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
==> digitalocean: E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
==> digitalocean: Provisioning step had errors: Running the cleanup provisioner, if present...
==> digitalocean: Destroying droplet...
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' errored after 3 minutes 9 seconds: Script exited with non-zero exit status: 100.Allowed exit codes are: [0]

==> Wait completed after 3 minutes 9 seconds

==> Some builds didn't complete successfully and had errors:
--> digitalocean: Script exited with non-zero exit status: 100.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.

**Comment by derrickmehaffy** [comment]
The one-click no longer exists, this repo is here as read-only.
