### ISSUE TITLE
[TO-DO] Move Strapi project generation to cloud-init

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/one-click-deploy#4]
Should move initial project creation to the cloud-init so we don't need to update images to use latest versions.

Need to discuss with @alexandrebodin and @pierreburgy about how best to handle this as we also want to avoid users creating projects that already have quick hot-fixes.

Should we stick to the existing system where each image is specifically constructed to use one version  or set it to use the latest?

**Comment by alexandrebodin** [comment]
@derrickmehaffy would be better to have one image per version so user can choose if they want for compatibilty reasons. Like the tags with docker. Automating this would be cool though

**Comment by derrickmehaffy** [comment]
Automation with DO will be difficult, we can certainly automate the generation of the images but DO's marketplace doesn't support multiple versions (and changing them is a manual process).

I had thought of a similar situation with PostgreSQL vs MySQL vs Mongo

**Comment by alexandrebodin** [comment]
If there are no versionning then the image should use the latest version for sure

**Comment by derrickmehaffy** [comment]
Alright I will look into migrating the project generation and DB creation into the cloud-init instead of pre-boot.

(Gonna do both the AWS/DO at the same time on this.)
